# Generated by Django 6.0 on 2026-01-05 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название оператора')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='operators/logo/', verbose_name='Логотип')),
                ('website', models.URLField(verbose_name='Сайт для парсинга')),
                ('color', models.CharField(default='#007bff', help_text='HEX-код цвета, например, #ff0000 для красного', max_length=7, verbose_name='Брендовый цвет')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, verbose_name='Описание условий')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Абонентская плата')),
                ('data_volume', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Включено ГБ')),
                ('minutes_volume', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Включено минут')),
                ('overage_data_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за дополнительный ГБ')),
                ('overage_minute_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за дополнительную минуту')),
                ('is_archived', models.BooleanField(default=False, help_text='Не отображается в основном поиске', verbose_name='Архивный тариф')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='comparison.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['operator', 'monthly_fee'],
                'unique_together': {('operator', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_monthly_data', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Плановый расход ГБ/мес')),
                ('avg_monthly_minutes', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Плановый расход минут/мес')),
                ('current_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='comparison.tariffplan', verbose_name='Текущий тариф')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='TariffComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_monthly_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рассчитанная стоимость')),
                ('user_data_input', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Введённые ГБ')),
                ('user_minutes_input', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Введённые минуты')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендовано')),
                ('comparison_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сравнения')),
                ('tariff_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='comparison.tariffplan')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='comparison.userprofile')),
            ],
            options={
                'verbose_name': 'Результат сравнения',
                'verbose_name_plural': 'История сравнений',
                'ordering': ['-comparison_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Год')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('actual_data_used', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фактический расход ГБ')),
                ('actual_minutes_used', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фактический расход минут')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_history', to='comparison.userprofile')),
            ],
            options={
                'verbose_name': 'Запись о потреблении',
                'verbose_name_plural': 'Журнал потребления',
                'ordering': ['-year', '-month'],
                'unique_together': {('user_profile', 'year', 'month')},
            },
        ),
    ]