# Generated by Django 6.0 on 2026-01-15 13:57

import os
from django.db import migrations
from django.core.files import File
from django.conf import settings

def load_initial_data(apps, schema_editor):
    # Получаем модель
    Operator = apps.get_model('comparison', 'Operator')
    # Получаем пути для логотипов
    logos_dir = os.path.join(settings.BASE_DIR, 'comparison', 'static', 'comparison', 'operators_logo')
    # Данные для заполнения
    operators_data = [
        {'name': 'МТС', 'logo': 'mts.png', 'website': 'https://e-burg.mts.ru/personal/mobilnaya-svyaz/tarifi/vse-tarifi/mobile', 'color': '#FF0032'},
        {'name': 'Мегафон', 'logo': 'megafon.png', 'website': 'https://svr.megafon.ru/tariffs/all/', 'color': '#00B956'},
        {'name': 'Билайн', 'logo': 'beeline.png', 'website': 'https://ekaterinburg.beeline.ru/customers/products/toptariffs/', 'color': '#FFC800'},
        {'name': 'Т2', 'logo': 't2.png', 'website': 'https://ekt.t2.ru/tariffs', 'color': '#FF3495'},
    ]
    
    for data in operators_data:
        logo_path = os.path.join(logos_dir, data['logo'])
        Operator.objects.create(**data)

def reverse_load_data(apps, schema_editor):
    # Функция для отката миграции
    Operator = apps.get_model('comparison', 'Operator')
    Operator.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_load_data),
    ]