# Generated by Django 6.0 on 2026-01-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0002_auto_20260115_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='logo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
