# Generated by Django 6.0 on 2026-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0003_alter_operator_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='logo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Путь до логотипа'),
        ),
    ]
